# STRUCTURE VALIDATION EXTRACTION

This notebook contians the necessary code to get the validation reports from the 3D structures in our dataset.

In [1]:
import pandas as pd
import numpy as np
import os
import structure_validation
import importlib

In [2]:
df = pd.read_pickle('files/anks_final_aln.sto_prointvar_structure_table.p.gz') # STRUCTURAL DATA TABLE

In [3]:
print(len(df))

243572

In [4]:
validation_dir = "files/structure_validation"
pdb_dir = "files/structure_validation/pdbx"  # prointvar downloads

In [5]:
structure_validation.download_validation(df, validation_dir) # DOWNLOADS VALIDATION DATA USING PROTEOFAV
rs_dict = structure_validation.get_rsrz_dict(df, validation_dir) # GETS DICT INDICATING WHICH PDBs HAVE RSRZ ON THEIR VALIDATION
struc_df = structure_validation.get_res_exp_from_df(df, pdb_dir) # GETS RESOLUTION AND EXPERIMENTAL METHOD USED FOR SOLVING EACH PDB
val_df = structure_validation.get_validation_df(df, validation_dir) # CONCATENATES ALL VALIDATION TABLES IN A BIG DF
validation_def = pd.merge(val_df, struc_df, on = "pdb_id") # MERGES VALIDATION DF WITH RESOLUTION AND EXP. DATA DF
merged_df = structure_validation.merge_with_validation(df, validation_def) # MERGES PREVIOUS DF WITH STRUCTURAL TABLE DATA

Validation for 3w9f already exists!
Validation for 3w9g already exists!
Validation for 3jxi already exists!
Validation for 3jxj already exists!
Validation for 4cj9 already exists!
Validation for 5d68 already exists!
Validation for 3v30 already exists!
Validation for 6mew already exists!
Validation for 3uxg already exists!
Validation for 3ui2 already exists!
Validation for 3deo already exists!
Validation for 3dep already exists!
Validation for 5e4w already exists!
Validation for 2pnn already exists!
Validation for 2nyj already exists!
Validation for 6hc8 already exists!
Validation for 1uoh already exists!
Validation for 4nik already exists!
Validation for 1qym already exists!
Validation for 5u0i already exists!
Validation for 5u0j already exists!
Validation for 5jhq already exists!
Validation for 6urq already exists!
Validation for 5gp7 already exists!
Validation for 1ot8 already exists!
Validation for 1sw6 already exists!
Validation for 2fo1 already exists!
Validation for 1n11 already exists!
Validation for 1k1a already exists!
Validation for 1k1b already exists!
Validation for 5h2c already exists!
Validation for 5h28 already exists!
Validation for 1bi7 already exists!
Validation for 1mx4 already exists!
Validation for 1mx6 already exists!
Validation for 1mx2 already exists!
Validation for 1g3n already exists!
Validation for 1ihb already exists!
Validation for 6py8 already exists!
Validation for 2f8x already exists!
Validation for 3nbn already exists!
Validation for 3v79 already exists!
Validation for 2he0 already exists!
Validation for 1yyh already exists!
Validation for 2f8y already exists!
Validation for 4bsz already exists!
Validation for 2dzn already exists!
Validation for 1ixv already exists!
Validation for 1wg0 already exists!
Validation for 2dzo already exists!
Validation for 1bi8 already exists!
Validation for 1bd8 already exists!
Validation for 7df7 already exists!
Validation for 7dsb already exists!
Validation for 7dsa already exists!
Validation for 1awc already exists!
Validation for 4ot9 already exists!
Validation for 4rlv already exists!
Validation for 5y4d already exists!
Validation for 5y4f already exists!
Validation for 4rly already exists!
Validation for 5y4e already exists!
Validation for 2qc9 already exists!
Validation for 1ymp already exists!
Validation for 3p3n already exists!
Validation for 3p3p already exists!
Validation for 6jd6 already exists!
Validation for 4oav already exists!
Validation for 4oau already exists!
Validation for 4g8k already exists!
Validation for 4g8l already exists!
Validation for 1wdy already exists!
Validation for 4hi8 already exists!
Validation for 4hi9 already exists!
Validation for 3f6q already exists!
Validation for 3ixe already exists!
Validation for 1ycs already exists!
Validation for 4a63 already exists!
Validation for 6ghm already exists!
Validation for 6hkp already exists!
Validation for 5ybu already exists!
Validation for 5ybj already exists!
Validation for 3jue already exists!
Validation for 3t9k already exists!
Validation for 4f1p already exists!
Validation for 6if3 already exists!
Validation for 5aar already exists!
Validation for 6kyk already exists!
Validation for 6kyh already exists!
Validation for 6sku already exists!
Validation for 4bes already exists!
Validation for 4bet already exists!
Validation for 4ber already exists!
Validation for 4bep already exists!
Validation for 1blx already exists!
Validation for 1oy3 already exists!
Validation for 1k3z already exists!
Validation for 4hbd already exists!
Validation for 5ybv already exists!
Validation for 6tmd already exists!
Validation for 6cf6 already exists!
Validation for 3utm already exists!
Validation for 5hkp already exists!
Validation for 1dcq already exists!
Validation for 2ft0 already exists!
Validation for 2fs5 already exists!
Validation for 3eu9 already exists!
Validation for 5w7i already exists!
Validation for 5w7j already exists!
Validation for 4n5q already exists!
Validation for 6l93 already exists!
Validation for 6ha6 already exists!
Validation for 6h9j already exists!
Validation for 3lvq already exists!
Validation for 3lvr already exists!
Validation for 2b0o already exists!
Validation for 2vge already exists!
Validation for 6dcx already exists!
Validation for 6rz3 already exists!
Validation for 6hl6 already exists!
Validation for 4uuc already exists!
Validation for 1s70 already exists!
Validation for 2rfa already exists!
Validation for 5z2n already exists!
Validation for 5z2m already exists!
Validation for 3ehr already exists!
Validation for 3ehq already exists!
Validation for 3zkj already exists!
Validation for 3zng already exists!
Validation for 3d9h already exists!
Validation for 5ja4 already exists!
Validation for 6lf0 already exists!
Validation for 6le6 already exists!
Validation for 6ldp already exists!
Validation for 6len already exists!
Validation for 6ley already exists!
Validation for 6lbg already exists!
Validation for 6lbn already exists!
Validation for 7jya already exists!
Validation for 6xkc already exists!
Validation for 6hl5 already exists!
Validation for 4b93 already exists!
Validation for 4cym already exists!
Validation for 4cz2 already exists!
Validation for 2rfm already exists!
Validation for 3c5r already exists!
Validation for 6iyb already exists!
Validation for 5et1 already exists!
Validation for 5et0 already exists!
Validation for 3twq already exists!
Validation for 5bxo already exists!
Validation for 5bxu already exists!
Validation for 3twr already exists!
Validation for 3tws already exists!
Validation for 3twu already exists!
Validation for 3twx already exists!
Validation for 3twt already exists!
Validation for 3tww already exists!
Validation for 3twv already exists!
Validation for 4z68 already exists!
Validation for 2y0i already exists!
Validation for 6by9 already exists!
Validation for 3hna already exists!
Validation for 3b7b already exists!
Validation for 3b95 already exists!
Validation for 4lg6 already exists!
Validation for 4qqi already exists!
Validation for 3v31 already exists!
Validation for 3v2x already exists!
Validation for 3v2o already exists!
Validation for 3so8 already exists!
Validation for 4dx1 already exists!
Validation for 4dx2 already exists!
Validation for 6jmt already exists!
Validation for 5g4x already exists!
Validation for 5wo7 already exists!
Validation for 5iwk already exists!
Validation for 6d7p already exists!
Validation for 5wo8 already exists!
Validation for 6d7o already exists!
Validation for 6d7q already exists!
Validation for 6d7x already exists!
Validation for 5iwp already exists!
Validation for 5wo9 already exists!
Validation for 5iwt already exists!
Validation for 5iwr already exists!
Validation for 5woa already exists!
Validation for 6d7v already exists!
Validation for 5wo6 already exists!
Validation for 5eid already exists!
Validation for 4tum already exists!
Validation for 3zrh already exists!
Validation for 5u0k already exists!
Validation for 6lbf already exists!
Validation for 7cng already exists!
Validation for 2etc already exists!
Validation for 2etb already exists!
Validation for 2eta already exists!
Validation for 2f37 already exists!
Validation for 6tlh already exists!
Validation for 3aji already exists!
Validation for 2dvw already exists!
Validation for 2dwz already exists!
Validation for 4hdo already exists!
Validation for 6oq4 already exists!
Validation for 6oq3 already exists!
Validation for 6uzk already exists!
Validation for 4hdq already exists!
Validation for 4i51 already exists!
3w9f processed successfully!
3w9g processed successfully!
3jxi processed successfully!
3jxj processed successfully!
4cj9 processed successfully!
5d68 processed successfully!
3v30 processed successfully!
6mew processed successfully!
3uxg processed successfully!
3ui2 processed successfully!
3deo processed successfully!
3dep processed successfully!
5e4w processed successfully!
2pnn processed successfully!
2nyj processed successfully!
6hc8 processed successfully!
1uoh processed successfully!
4nik processed successfully!
1qym processed successfully!
5u0i processed successfully!
5u0j processed successfully!
5jhq processed successfully!
6urq processed successfully!
5gp7 processed successfully!
1ot8 processed successfully!
1sw6 processed successfully!
2fo1 processed successfully!
1n11 processed successfully!
1k1a processed successfully!
1k1b processed successfully!
5h2c processed successfully!
5h28 processed successfully!
1bi7 processed successfully!
1mx4 processed successfully!
1mx6 processed successfully!
1mx2 processed successfully!
1g3n processed successfully!
1ihb processed successfully!
6py8 processed successfully!
2f8x processed successfully!
3nbn processed successfully!
3v79 processed successfully!
2he0 processed successfully!
1yyh processed successfully!
2f8y processed successfully!
4bsz processed successfully!
2dzn processed successfully!
1ixv processed successfully!
1wg0 processed successfully!
2dzo processed successfully!
1bi8 processed successfully!
1bd8 processed successfully!
7df7 processed successfully!
7dsb processed successfully!
7dsa processed successfully!
1awc processed successfully!
4ot9 processed successfully!
4rlv processed successfully!
5y4d processed successfully!
5y4f processed successfully!
4rly processed successfully!
5y4e processed successfully!
2qc9 processed successfully!
1ymp processed successfully!
3p3n processed successfully!
3p3p processed successfully!
6jd6 processed successfully!
4oav processed successfully!
4oau processed successfully!
4g8k processed successfully!
4g8l processed successfully!
1wdy processed successfully!
4hi8 processed successfully!
4hi9 processed successfully!
3f6q processed successfully!
3ixe processed successfully!
1ycs processed successfully!
4a63 processed successfully!
6ghm processed successfully!
6hkp processed successfully!
5ybu processed successfully!
5ybj processed successfully!
3jue processed successfully!
3t9k processed successfully!
4f1p processed successfully!
6if3 processed successfully!
5aar processed successfully!
6kyk processed successfully!
6kyh processed successfully!
6sku processed successfully!
4bes processed successfully!
4bet processed successfully!
4ber processed successfully!
4bep processed successfully!
1blx processed successfully!
1oy3 processed successfully!
1k3z processed successfully!
4hbd processed successfully!
5ybv processed successfully!
6tmd processed successfully!
6cf6 processed successfully!
3utm processed successfully!
5hkp processed successfully!
1dcq processed successfully!
2ft0 processed successfully!
2fs5 processed successfully!
3eu9 processed successfully!
5w7i processed successfully!
5w7j processed successfully!
4n5q processed successfully!
6l93 processed successfully!
6ha6 processed successfully!
6h9j processed successfully!
3lvq processed successfully!
3lvr processed successfully!
2b0o processed successfully!
2vge processed successfully!
6dcx processed successfully!
6rz3 processed successfully!
6hl6 processed successfully!
4uuc processed successfully!
1s70 processed successfully!
2rfa processed successfully!
5z2n processed successfully!
5z2m processed successfully!
3ehr processed successfully!
3ehq processed successfully!
3zkj processed successfully!
3zng processed successfully!
3d9h processed successfully!
5ja4 processed successfully!
6lf0 processed successfully!
6le6 processed successfully!
6ldp processed successfully!
6len processed successfully!
6ley processed successfully!
6lbg processed successfully!
6lbn processed successfully!
7jya processed successfully!
6xkc processed successfully!
6hl5 processed successfully!
4b93 processed successfully!
4cym processed successfully!
4cz2 processed successfully!
2rfm processed successfully!
3c5r processed successfully!
6iyb processed successfully!
5et1 processed successfully!
5et0 processed successfully!
3twq processed successfully!
5bxo processed successfully!
5bxu processed successfully!
3twr processed successfully!
3tws processed successfully!
3twu processed successfully!
3twx processed successfully!
3twt processed successfully!
3tww processed successfully!
3twv processed successfully!
4z68 processed successfully!
2y0i processed successfully!
6by9 processed successfully!
3hna processed successfully!
3b7b processed successfully!
3b95 processed successfully!
4lg6 processed successfully!
4qqi processed successfully!
3v31 processed successfully!
3v2x processed successfully!
3v2o processed successfully!
3so8 processed successfully!
4dx1 processed successfully!
4dx2 processed successfully!
6jmt processed successfully!
5g4x processed successfully!
5wo7 processed successfully!
5iwk processed successfully!
6d7p processed successfully!
5wo8 processed successfully!
6d7o processed successfully!
6d7q processed successfully!
6d7x processed successfully!
5iwp processed successfully!
5wo9 processed successfully!
5iwt processed successfully!
5iwr processed successfully!
5woa processed successfully!
6d7v processed successfully!
5wo6 processed successfully!
5eid processed successfully!
4tum processed successfully!
3zrh processed successfully!
5u0k processed successfully!
6lbf processed successfully!
7cng processed successfully!
2etc processed successfully!
2etb processed successfully!
2eta processed successfully!
2f37 processed successfully!
6tlh processed successfully!
3aji processed successfully!
2dvw processed successfully!
2dwz processed successfully!
4hdo processed successfully!
6oq4 processed successfully!
6oq3 processed successfully!
6uzk processed successfully!
4hdq processed successfully!
4i51 processed successfully!
3w9f validation appended successfully!
3w9g validation appended successfully!
3jxi validation appended successfully!
3jxj validation appended successfully!
4cj9 validation appended successfully!
5d68 validation appended successfully!
3v30 validation appended successfully!
6mew validation appended successfully!
3uxg validation appended successfully!
3ui2 validation appended successfully!
3deo validation appended successfully!
3dep validation appended successfully!
5e4w validation appended successfully!
2pnn validation appended successfully!
2nyj validation appended successfully!
6hc8 validation appended successfully!
1uoh validation appended successfully!
4nik validation appended successfully!
1qym validation appended successfully!
5u0i validation appended successfully!
5u0j validation appended successfully!
5jhq validation appended successfully!
6urq validation appended successfully!
5gp7 validation appended successfully!
1ot8 validation appended successfully!
1sw6 validation appended successfully!
2fo1 validation appended successfully!
1n11 validation appended successfully!
1k1a validation appended successfully!
1k1b validation appended successfully!
5h2c validation appended successfully!
5h28 validation appended successfully!
1bi7 validation appended successfully!
1mx4 validation appended successfully!
1mx6 validation appended successfully!
1mx2 validation appended successfully!
1g3n validation appended successfully!
1ihb validation appended successfully!
6py8 validation appended successfully!
2f8x validation appended successfully!
3nbn validation appended successfully!
3v79 validation appended successfully!
2he0 validation appended successfully!
1yyh validation appended successfully!
2f8y validation appended successfully!
4bsz validation appended successfully!
2dzn validation appended successfully!
1ixv validation appended successfully!
1wg0 validation appended successfully!
2dzo validation appended successfully!
1bi8 validation appended successfully!
1bd8 validation appended successfully!
7df7 validation appended successfully!
7dsb validation appended successfully!
7dsa validation appended successfully!
1awc validation appended successfully!
4ot9 validation appended successfully!
4rlv validation appended successfully!
5y4d validation appended successfully!
5y4f validation appended successfully!
4rly validation appended successfully!
5y4e validation appended successfully!
2qc9 validation appended successfully!
1ymp validation appended successfully!
3p3n validation appended successfully!
3p3p validation appended successfully!
6jd6 validation appended successfully!
4oav validation appended successfully!
4oau validation appended successfully!
4g8k validation appended successfully!
4g8l validation appended successfully!
1wdy validation appended successfully!
4hi8 validation appended successfully!
4hi9 validation appended successfully!
3f6q validation appended successfully!
3ixe validation appended successfully!
1ycs validation appended successfully!
4a63 validation appended successfully!
6ghm validation appended successfully!
6hkp validation appended successfully!
5ybu validation appended successfully!
5ybj validation appended successfully!
3jue validation appended successfully!
3t9k validation appended successfully!
4f1p validation appended successfully!
6if3 validation appended successfully!
5aar validation appended successfully!
6kyk validation appended successfully!
6kyh validation appended successfully!
6sku validation appended successfully!
4bes validation appended successfully!
4bet validation appended successfully!
4ber validation appended successfully!
4bep validation appended successfully!
1blx validation appended successfully!
1oy3 validation appended successfully!
1k3z validation appended successfully!
4hbd validation appended successfully!
5ybv validation appended successfully!
6tmd validation appended successfully!
6cf6 validation appended successfully!
3utm validation appended successfully!
5hkp validation appended successfully!
1dcq validation appended successfully!
2ft0 validation appended successfully!
2fs5 validation appended successfully!
3eu9 validation appended successfully!
5w7i validation appended successfully!
5w7j validation appended successfully!
4n5q validation appended successfully!
6l93 validation appended successfully!
6ha6 validation appended successfully!
6h9j validation appended successfully!
3lvq validation appended successfully!
3lvr validation appended successfully!
2b0o validation appended successfully!
2vge validation appended successfully!
6dcx validation appended successfully!
6rz3 validation appended successfully!
6hl6 validation appended successfully!
4uuc validation appended successfully!
1s70 validation appended successfully!
2rfa validation appended successfully!
5z2n validation appended successfully!
5z2m validation appended successfully!
3ehr validation appended successfully!
3ehq validation appended successfully!
3zkj validation appended successfully!
3zng validation appended successfully!
3d9h validation appended successfully!
5ja4 validation appended successfully!
6lf0 validation appended successfully!
6le6 validation appended successfully!
6ldp validation appended successfully!
6len validation appended successfully!
6ley validation appended successfully!
6lbg validation appended successfully!
6lbn validation appended successfully!
7jya validation appended successfully!
6xkc validation appended successfully!
6hl5 validation appended successfully!
4b93 validation appended successfully!
4cym validation appended successfully!
4cz2 validation appended successfully!
2rfm validation appended successfully!
3c5r validation appended successfully!
6iyb validation appended successfully!
5et1 validation appended successfully!
5et0 validation appended successfully!
3twq validation appended successfully!
5bxo validation appended successfully!
5bxu validation appended successfully!
3twr validation appended successfully!
3tws validation appended successfully!
3twu validation appended successfully!
3twx validation appended successfully!
3twt validation appended successfully!
3tww validation appended successfully!
3twv validation appended successfully!
4z68 validation appended successfully!
2y0i validation appended successfully!
6by9 validation appended successfully!
3hna validation appended successfully!
3b7b validation appended successfully!

In [ ]:
merged_df.head()

,AA_A,AA_B,ACC_A,ACC_B,ACC_UNB_A,ACC_UNB_B,ALPHA_A,ALPHA_B,ATOM_A,ATOM_B,...,validation_resnum_B,validation_resnum_full_B,validation_rota_B,validation_rscc_B,validation_rsr_B,validation_rsrz_B,validation_said_B,validation_seq_B,experiment_B,resolution_B
0,Q,A,23.0,1.0,23.0,1.0,-165.9,59.6,C,N,...,227,227,nan,0.973,0.191,1.8130000000000002,A,96,X-RAY DIFFRACTION,1.9
1,A,L,1.0,1.0,1.0,1.0,59.6,46.9,C,CD1,...,243,243,mt,0.9520000000000001,0.15,0.846,A,112,X-RAY DIFFRACTION,1.9
2,L,L,1.0,1.0,1.0,1.0,52.9,46.9,CA,CD1,...,243,243,mt,0.9520000000000001,0.15,0.846,A,112,X-RAY DIFFRACTION,1.9
3,A,L,0.0,1.0,0.0,1.0,45.2,46.9,CB,CD1,...,243,243,mt,0.9520000000000001,0.15,0.846,A,112,X-RAY DIFFRACTION,1.9
4,Y,L,2.0,1.0,2.0,1.0,57.1,46.9,O,N,...,243,243,mt,0.9520000000000001,0.15,0.846,A,112,X-RAY DIFFRACTION,1.9

In [ ]:
print(len(structure_validation.filter_rsrz_rscc(merged_df)))

140694

In [ ]:
merged_df.to_csv("/cluster/gjb_lab/2394007/varalign_runs/varalign_bio_units4/.varalign/prointvar_analysis_data/anks_final_aln.sto_prointvar_structure_table_with_validation.csv")

## ONCE IT HAS BEEN RUN, THE DF CAN JUST BE LOADED

In [ ]:
df_allsp = pd.read_csv("/cluster/gjb_lab/2394007/varalign_runs/varalign_bio_units4/.varalign/prointvar_analysis_data/anks_final_aln.sto_prointvar_structure_table_with_validation.csv")

2021-05-17 10:29:47,585 - WARNING - /cluster/gjb_lab/2394007/miniconda/envs/varalign-env-py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (2,15,16,19,20,26,27,29,30,32,34,42,43,44,45,46,47,48,49,52,53,64,65,66,68,70,72,76,77,78,92,96,114,116,119,120,123,124,129,130,133,134,143,144,150,152,154,156,158,162,164,170,207,209,214,215,231,232,233,234,235,244,275,279,281,282,285,301,302,305,309,311) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
df_allsp_rsrz_filt = structure_validation.filter_rsrz_rscc(df_allsp) 
print(len(df_allsp_rsrz_filt))

140694

In [ ]:
df_allsp_rsrz_filt.head()

,Unnamed: 0,AA_A,AA_B,ACC_A,ACC_B,ACC_UNB_A,ACC_UNB_B,ALPHA_A,ALPHA_B,ATOM_A,...,validation_resnum_B,validation_resnum_full_B,validation_rota_B,validation_rscc_B,validation_rsr_B,validation_rsrz_B,validation_said_B,validation_seq_B,experiment_B,resolution_B
0,0,Q,A,23.0,1.0,23.0,1.0,-165.9,59.6,C,...,227.0,227.0,NaN,0.973,0.191,1.813,A,96.0,X-RAY DIFFRACTION,1.9
1,1,A,L,1.0,1.0,1.0,1.0,59.6,46.9,C,...,243.0,243.0,mt,0.952,0.150,0.846,A,112.0,X-RAY DIFFRACTION,1.9
2,2,L,L,1.0,1.0,1.0,1.0,52.9,46.9,CA,...,243.0,243.0,mt,0.952,0.150,0.846,A,112.0,X-RAY DIFFRACTION,1.9
3,3,A,L,0.0,1.0,0.0,1.0,45.2,46.9,CB,...,243.0,243.0,mt,0.952,0.150,0.846,A,112.0,X-RAY DIFFRACTION,1.9
4,4,Y,L,2.0,1.0,2.0,1.0,57.1,46.9,O,...,243.0,243.0,mt,0.952,0.150,0.846,A,112.0,X-RAY DIFFRACTION,1.9